language: go

go:
  - 1.10.x
  - 1.11.x
  - tip

go_import_path: gopkg.in/src-d/go-mysql-server.v0

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

sudo: required

services:
  - docker

before_install:
  - docker pull pilosa/pilosa:v0.9.0
  - docker run -d --name pilosa -p 127.0.0.1:10101:10101 pilosa/pilosa:v0.9.0
  - docker ps -a

install:
  - go get -u github.com/golang/dep/cmd/dep
  - touch Gopkg.toml
  - dep ensure -v -add "github.com/pilosa/go-pilosa@0.9.0" "github.com/pilosa/pilosa@1.0.2"
  - make dependencies

script:
  - make ci-script
